version: '3'
services:
  lex:
    image: mysql:latest 
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user

volumes:
  data:
